// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_ConservedWriter_p3_CLASS_HEADER_
#define POSTPROCESSING_ConservedWriter_p3_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace SWE {
  class MySWESolver_p3;
  class ConservedWriter_p3;
}

class SWE::ConservedWriter_p3 : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  ConservedWriter_p3(SWE::MySWESolver_p3& solver);
  virtual ~ConservedWriter_p3();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_ConservedWriter_p3_CLASS_HEADER_ */