/* This file is autogenerated by generate-buildinfo.sh */

#ifndef _EXAHYPE_BUILD_INFO_H_
#define _EXAHYPE_BUILD_INFO_H_

#define EXAHYPE_BUILDINFO_AVAILABLE
#define EXAHYPE_BUILD_DATE          "Tue Nov 24 11:27:16 CET 2020"
#define EXAHYPE_BUILD_HOST          "login01"

/* Strings passed by the Makefile */
#define EXAHYPE_BUILD_INFO \
    "COMPILER = Intel\n" \
    "MODE = Release\n" \
    "SHAREDMEM = TBB\n" \
    "DISTRIBUTEDMEM = MPI\n" \
    "------\n" \
    "ARCHITECTURE = hsw\n" \
    "CC = mpiicpc\n" \
    "BOUNDARYCONDITIONS = None\n" \
    "------\n" \
    "COMPILER_CFLAGS = -DEXAHYPE_LATE_TAKEOVER -DTrackGridStatistics -restrict -std=c++11 -pedantic -Wall -qopenmp-simd -O3 -ip -xCORE-AVX2 -fma -DSharedTBB -DParallel -DnoPackedRecords -DnoPersistentRegularSubtrees  -DIprobeEveryKIterations=0 -DUsePeanosRLEBoundaryExchanger -DUsePeanosRLEBoundaryExchangerForMetaData\n" \
    "COMPILER_LFLAGS = -g -ltbb -L/dss/dsshome1/lrz/sys/spack/release/19.1/opt/x86_avx512/gsl/2.3-intel-r55eslv/lib -lgslcblas -L/dss/dsshome1/lrz/sys/spack/release/19.1/opt/x86_avx512/gsl/2.3-intel-r55eslv/lib -lgsl -xCORE-AVX2 -fma\n" \
    "FCOMPILER_CFLAGS = -r8 -cpp -auto -qopenmp-simd -O2 -xCORE-AVX2 -fma\n" \
    "FCOMPILER_LFLAGS = \n" \
    "------\n" \
    "EXAHYPE_PATH = /dss/dsshome1/0C/ge68wax4/MUQ/ExaHyPE-Engine/./ExaHyPE\n" \
    "PROJECT_PATH = /dss/dsshome1/0C/ge68wax4/MUQ/ExaHyPE-Engine/./ApplicationExamples/SWE/SWE_MC_ADERDG\n" \
    "PEANO_KERNEL_PEANO_PATH = /dss/dsshome1/0C/ge68wax4/MUQ/ExaHyPE-Engine/./Peano/peano\n" \
    "PEANO_KERNEL_TARCH_PATH = /dss/dsshome1/0C/ge68wax4/MUQ/ExaHyPE-Engine/./Peano/tarch\n" \
    "------\n" \
    "PROJECT_CFLAGS = -DDim2 -DALIGNMENT=32\n" \
    "PROJECT_LFLAGS = \n" \
    ""


/*
 * ExaHyPE Git Repository information extraction
 * Extracted from git repository in /dss/dsshome1/0C/ge68wax4/MUQ/ExaHyPE-Engine/./ExaHyPE
 */

/* Information collected with git version 2.22.0 */
#define EXAHYPE_GIT_INFO "reinarz/muq  6162b1e7f Tue Nov 24 10:56:42 2020"

/*
 * Peano Git Repository information extraction
 * Extracted from git repository in /dss/dsshome1/0C/ge68wax4/MUQ/ExaHyPE-Engine/./Peano/peano
 */

/* Information collected with git version 2.22.0 */
#define PEANO_GIT_INFO "muq  c457c711 Tue Sep 15 21:47:11 2020"
#define PEANO_SVN_INFO  PEANO_GIT_INFO /* transition time */

/*
    Peano version check

    FIXME TODO This is the worst place ever to hook in version
               requirements. Please move the following to somewhere
               suitable, such as the Peano startup phase.

*/

#include "peano/version.h"

#endif /* EXAHYPE_BUILD_INFO_H */
#if PEANO_VERSION<2509 
#error Old Peano version. Version 2509 required. Please update your Peano installation.
#endif
